HAPPEN MVC/Components/MenuViewComponent.cs
using HAPPAN_MVC.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HAPPAN_MVC.Components
{
    public class MenuViewComponent : ViewComponent
    {
        private readonly HAPPANDBContext hAPPAN_MVC_AuthDBContext;
        public MenuViewComponent(HAPPANDBContext hAPPAN_MVC_AuthDBContext)
        {
            this.hAPPAN_MVC_AuthDBContext = hAPPAN_MVC_AuthDBContext;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = hAPPAN_MVC_AuthDBContext.Projects.ToList();
            return await Task.FromResult((IViewComponentResult)View("Menu", model));
        }

    }

}

HAPPEN MVC/Controllers/AddProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HAPPAN_MVC.Data;
using HAPPAN_MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace HAPPAN.Controllers
{
    public class AddProjectController : Controller
    {

        private readonly HAPPANDBContext hAPPAN_MVC_AuthDBContext;

        public AddProjectController(HAPPANDBContext hAPPAN_MVC_AuthDBContext)
        {
            this.hAPPAN_MVC_AuthDBContext = hAPPAN_MVC_AuthDBContext;
        }

        // GET: Project/Create
        public IActionResult Index(int id = 0)
        {
            if (id == 0)
                return View(new Project());
            else
            
                return View(hAPPAN_MVC_AuthDBContext.Projects.Find(id));
        }

        // POST: Project/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index([Bind("ProjectId,ProjectName,Status")] Project Projects)
        {
            if (ModelState.IsValid)
            {
                if (Projects.ProjectId == 0)
                    hAPPAN_MVC_AuthDBContext.Add(Projects);
                else
                    hAPPAN_MVC_AuthDBContext.Update(Projects);
                await hAPPAN_MVC_AuthDBContext.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }
            return View(Projects);
        }

    }
}

HAPPEN MVC/Controllers/ProposalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HAPPAN.Controllers
{
    public class ProposalController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

HAPPEN MVC/Views/Shared/Components/Menu/Menu.cshtml
@model IList<Project>

    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
    with font-awesome or any other icon font library -->
        <li class="nav-item menu-open">
            <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link active">
                <i class="nav-icon fas fa-tachometer-alt"></i>
                <p>
                    Dashboard

                </p>
            </a>

        </li>
        <li class="nav-header">Projects</li>
        <li class="nav-item">
            <a asp-area="" asp-controller="AddProject" asp-action="Index" class="nav-link">
                <i class="nav-icon fas fa-th"></i>
                <p>
                    Add Projects

                </p>
            </a>
        </li>

        <li class="nav-item menu-open">
            <a href="#" class="nav-link">
                <i class="nav-icon fas fa-puzzle-piece"></i>
                <p>
                    Current Projects
                    <i class="right fas fa-angle-left"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">

                @foreach (var project in Model)
                {
                    <li class="nav-item">
                        <a class="nav-link " href="/CurrentProject/Info?projectId=@project.ProjectId">
                            <i class="far fa-circle nav-icon"></i>
                            <p>@project.ProjectName</p>
                        </a>
                    </li>
                }
            </ul>
        </li>

        <li class="nav-header">Proposal</li>
        <li class="nav-item">
            <a asp-area="" asp-controller="Proposal" asp-action="Index" class="nav-link">
                <i class="nav-icon fas fa-th"></i>
                <p>
                    Proposal
                </p>
            </a>
        </li>

    </ul>